version: "3.9"

services:
  # ---------- Product Service's own database ----------
  product-db:
    image: postgres:16
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
      - ./product-service/init:/docker-entrypoint-initdb.d

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: product-db
      DB_PORT: 5432
      DB_USER: product_user
      DB_PASSWORD: product_pass
      DB_NAME: product_db
      PORT: 3001
    depends_on:
      - product-db

  # ---------- Order Service's own database ----------
  order-db:
    image: postgres:16
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./order-service/init:/docker-entrypoint-initdb.d

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: order-db
      DB_PORT: 5432
      DB_USER: order_user
      DB_PASSWORD: order_pass
      DB_NAME: order_db
      PORT: 3002
      PRODUCT_SERVICE_URL: http://product-service:3001   # ← the internal address
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      order-db:
        condition: service_started
      product-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  # ---------- Message broker for async events ----------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ---------- Services will be added below as we build each one ----------
  # product-service:
  # order-service:
  # notification-service:
  # api-gateway:

volumes:
  product_db_data:
  order_db_data: